
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[388] =
    {   0,
        0,    0,  111,  109,  108,  107,   95,  109,    1,  101,
       94,  109,   89,   90,   99,   98,   86,   97,   93,  100,
       52,   51,   87,   83,  102,   88,  103,  106,   49,   49,
       91,   92,  104,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   84,
      105,   85,   96,  108,  107,   82,    0,   60,    0,    1,
       68,   85,   77,   69,    0,    0,   66,   74,   64,   75,
       65,   76,    0,   55,    2,    3,   67,   56,   52,    0,
        0,   52,   52,    0,   52,   51,   51,   51,   51,   92,
       84,   91,   73,   79,   81,   80,   72,   49,    0,    0,

       70,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   11,   49,   49,   49,
       49,   49,   49,   19,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   71,   78,   60,    0,
        0,    0,    0,   53,    0,    0,   61,    0,   55,    3,
        0,   56,    0,   54,   52,   52,   52,   52,    0,   50,
       51,   51,   51,   51,   63,   62,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   17,   49,   49,
       21,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,    0,    0,    0,
        0,    0,   55,    0,   56,   54,   52,    0,    0,   50,
        0,   50,   50,   51,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,    4,   49,    6,    7,   49,   49,
       49,   49,   13,   14,   49,   49,   18,   49,   22,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   35,   49,   49,    0,    0,    0,    0,    0,    0,
       50,   50,    0,   57,   50,   50,   49,   49,   41,   49,
       49,   49,   49,   49,   49,   49,    5,    8,   49,   49,
       49,   49,   16,   49,   49,   49,   49,   26,   49,   49,

       49,   49,   49,   49,   33,   49,   49,   37,    0,   58,
        0,   59,   57,   50,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   12,   15,   20,   49,   49,
       25,   27,   28,   29,   30,   31,   49,   49,   49,   58,
       59,   49,   49,   40,   49,   49,   49,   49,   49,   49,
       49,   49,   10,   49,   49,   32,   49,   49,   38,   39,
       42,   43,   49,   49,   49,   49,   48,    9,   23,   24,
       34,   36,   49,   45,   49,   49,   44,   49,   49,   49,
       49,   49,   49,   49,   47,   46,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[399] =
    {   0,
        0,    0,  702,  703,  699,    0,  675,   72,  693,   53,
       72,  653,  703,  703,  672,   68,  703,   69,   67,   79,
      102,   82,  670,  703,   83,  670,   84,  703,    0,  106,
      703,  703,  669,  102,  626,  628,   50,   63,   67,   30,
      629,   92,  628,  636,   91,  617,  147,  625,  630,  703,
       88,  703,  703,  683,    0,  703,  128,  149,  140,  703,
      703,  703,  703,  703,  118,  147,  703,  703,  703,  703,
      703,  703,  668,  160,  703,    0,  703,  169,  211,  218,
      236,  133,  137,  667,  140,  226,  198,  139,  153,  703,
      703,  703,  657,  703,  703,  703,  656,    0,  159,  635,

      703,  118,  617,  616,  624,  616,  613,  608,  617,  618,
      605,  617,  604,  619,  606,  612,  598,  599,  596,  596,
      599,  596,  593,    0,  152,  597,  160,  595,  113,  145,
      599,  592,  649,  176,  146,  596,  703,  703,  257,  647,
      247,  255,    0,  703,  257,    0,  703,  268,  703,    0,
      277,  703,  285,  289,  249,  703,  614,  591,    0,  295,
      271,  703,  612,  589,  703,  703,  590,  584,  583,  584,
      582,  593,  577,  591,  575,  571,  575,  587,  582,  570,
      249,  584,  582,  578,  570,  576,  579,    0,  565,  569,
        0,  570,  567,  557,  555,  557,  559,  566,  552,  550,

      550,  562,  536,  538,  542,  543,  529,  312,  358,  310,
      404,  321,  347,  326,  408,  703,  703,  238,  273,  283,
      379,  290,  293,  703,  532,  525,  514,  508,  509,  498,
      497,  483,  495,  486,    0,  487,    0,    0,  478,  486,
      475,  482,    0,    0,  476,  473,    0,  477,    0,  472,
      472,  471,  468,  480,  470,  474,  479,  476,  474,  463,
      466,    0,  454,  466,  216,    0,  273,    0,  450,  459,
      314,  703,  351,  463,  481,  457,  454,  457,    0,  450,
      444,  450,  439,  447,  454,  450,    0,    0,  438,  439,
      444,  434,    0,  441,  427,  435,  430,    0,  434,  431,

      425,  409,  417,  413,    0,  403,  404,    0,  396,  469,
      400,  492,  703,  703,  302,  409,  406,  395,  390,  383,
      397,  395,  398,  377,  377,    0,    0,    0,  389,  389,
        0,    0,    0,    0,    0,    0,  385,  385,  372,  703,
      703,  365,  351,    0,  334,  351,  347,  331,  345,  337,
      335,  329,    0,  311,  308,    0,  321,  308,    0,    0,
        0,    0,  295,  292,  284,  264,    0,    0,    0,    0,
        0,    0,  250,    0,  219,  218,    0,  207,  218,  171,
      134,  107,   70,   16,    0,    0,  703,  551,  560,  569,
      573,  580,  587,  596,  601,  603,  605,  607

    } ;

static const flex_int16_t yy_def[399] =
    {   0,
      387,    1,  387,  387,  387,  388,  387,  389,  387,  387,
      387,  390,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  391,  391,
      387,  387,  387,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  387,
      387,  387,  387,  387,  388,  387,  389,  387,  392,  387,
      387,  387,  387,  387,  390,  393,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  394,  387,  387,  387,  387,
      387,  387,  387,  395,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  391,  389,  390,

      387,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  387,  387,  387,  387,
      387,  389,  396,  387,  390,  397,  387,  387,  387,  394,
      387,  387,  387,  387,  387,  387,  387,  387,  398,  395,
      387,  387,  387,  387,  387,  387,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  389,  389,  390,
      390,  387,  387,  387,  387,  387,  387,  398,  398,  387,
      387,  387,  387,  387,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  389,  209,  390,  211,  387,  387,
      387,  387,  387,  387,  387,  387,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  387,  387,
      387,  387,  387,  387,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  387,
      387,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,    0,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387

    } ;

static const flex_int16_t yy_nxt[780] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   30,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   29,   43,   29,
       29,   29,   29,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   58,   61,   62,   63,
       68,  386,   73,   70,   74,   74,   74,   74,  121,   91,
       75,  122,   69,   71,   72,   76,   64,   78,  113,   86,

       86,   86,   86,   77,   92,  114,   93,   94,   96,   97,
       99,  115,  137,   81,  100,  116,   59,   78,   87,   79,
       79,   80,   80,   88,  117,  118,  144,  119,  385,  102,
      103,  104,   58,   81,   81,  105,  120,  106,   82,  107,
       89,  108,  109,   83,   84,  124,  128,  129,   88,  110,
      139,   99,  125,   99,   81,  100,  130,  142,  142,  131,
       85,  138,   66,   58,  145,  145,  133,  197,   83,  155,
      384,   84,   59,  157,  156,  163,  167,   74,   74,   74,
       74,  156,  383,  168,  198,  140,   74,   74,   74,   74,
      140,  148,  149,  199,  162,  158,  149,  164,  155,  156,

      151,  152,  205,   59,  206,  152,  156,  134,  200,  143,
      190,  161,  148,  149,  193,  141,  146,  191,  149,  162,
       58,  151,  152,  382,  194,  195,   78,  152,   79,   79,
       80,   80,  203,   78,  161,   80,   80,   80,   80,  162,
      204,   78,   81,   86,   86,   86,   86,   82,  153,   81,
      153,   99,   83,  154,  154,  154,  154,   81,  139,   58,
       59,   99,   87,   81,  162,  144,  140,   88,  381,   85,
       81,  380,  208,  208,  210,  210,  269,   83,   81,  379,
      212,  144,  212,  378,   89,  213,  213,  213,  213,  214,
      156,  214,   88,  140,  215,  215,  215,  215,  140,   59,

      269,   66,  154,  154,  154,  154,  154,  154,  154,  154,
      219,  270,  162,  239,  240,  156,   58,   66,  144,  271,
      377,  216,  376,  141,  272,  216,  275,  267,  267,  265,
      265,  220,  375,  221,  272,  270,  222,  162,  213,  213,
      213,  213,  216,  215,  215,  215,  215,  216,  276,  272,
      342,  271,  374,  223,   66,  272,   59,  221,  373,  272,
      372,  222,   58,  343,  213,  213,  213,  213,  274,  274,
      274,  274,  371,  370,  369,  266,  266,  266,  266,  149,
      272,  368,  367,  149,  366,  266,  266,  266,  266,  266,
      266,  273,  365,  273,  364,  363,  274,  274,  274,  274,

      149,  362,   59,  361,  360,  149,  266,  266,  266,  266,
      266,  266,  144,  310,  310,  310,  310,  312,  312,  312,
      312,  268,  268,  268,  268,  215,  215,  215,  215,  359,
      358,  268,  268,  268,  268,  268,  268,  357,  356,  355,
      152,  354,  353,  352,  152,  351,  350,  349,   66,  348,
      347,  346,  268,  268,  268,  268,  268,  268,  345,  344,
      339,  152,  309,  338,  309,  337,  152,  310,  310,  310,
      310,  311,  336,  311,  335,  334,  312,  312,  312,  312,
      274,  274,  274,  274,  333,  332,  310,  310,  310,  310,
      331,  330,  329,  328,  327,  313,  326,  325,  324,  313,

      323,  340,  322,  321,  320,  340,  319,  318,  317,  312,
      312,  312,  312,  316,  315,  314,  313,  314,  308,  307,
      306,  313,  340,  305,  341,  304,  303,  340,  341,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  341,  286,  285,  284,  283,
      341,   55,  282,   55,   55,   55,   55,   55,   55,   55,
       57,  281,   57,   57,   57,   57,   57,   57,   57,   65,
      280,   65,  279,   65,   65,   65,   65,   65,   98,   98,
       98,   98,   57,   57,  278,   57,  277,  264,   57,   65,
       65,  263,   65,  262,  261,   65,  150,  260,  150,  150,

      150,  150,  150,  150,  150,  160,  160,  160,  209,  209,
      211,  211,  218,  218,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  224,  217,
      217,   99,  207,   99,  202,  201,  196,  192,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,   66,
      166,  165,  159,  147,   54,  136,  135,  132,  127,  126,
      123,  112,  111,  101,   95,   90,   67,   66,   60,   56,

       54,  387,    3,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387
    } ;

static const flex_int16_t yy_chk[780] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   10,   10,   11,
       16,  384,   19,   18,   19,   19,   19,   19,   40,   25,
       20,   40,   16,   18,   18,   20,   11,   22,   37,   22,

       22,   22,   22,   20,   25,   37,   25,   25,   27,   27,
       30,   37,   51,   22,   30,   38,    8,   21,   22,   21,
       21,   21,   21,   22,   38,   39,   65,   39,  383,   34,
       34,   34,   57,   21,   22,   34,   39,   34,   21,   34,
       22,   34,   34,   21,   21,   42,   45,   45,   22,   34,
       58,   47,   42,   58,   21,   47,   45,   59,   59,   45,
       21,   51,   65,   99,   66,   66,   47,  129,   21,   82,
      382,   21,   57,   83,   82,   88,  102,   74,   74,   74,
       74,   85,  381,  102,  129,   58,   78,   78,   78,   78,
       58,   74,   74,  130,   89,   83,   74,   88,   85,   82,

       78,   78,  135,   99,  135,   78,   85,   47,  130,   59,
      125,   89,   74,   74,  127,   58,   66,  125,   74,   89,
      265,   78,   78,  380,  127,  127,   79,   78,   79,   79,
       79,   79,  134,   80,   87,   80,   80,   80,   80,   87,
      134,   86,   79,   86,   86,   86,   86,   79,   81,   80,
       81,  141,   79,   81,   81,   81,   81,   86,  139,  142,
      265,  139,   86,   79,   87,  145,  141,   86,  379,   79,
       80,  378,  142,  142,  145,  145,  218,   79,   86,  376,
      148,  267,  148,  375,   86,  148,  148,  148,  148,  151,
      155,  151,   86,  139,  151,  151,  151,  151,  139,  142,

      218,  145,  153,  153,  153,  153,  154,  154,  154,  154,
      160,  219,  161,  181,  181,  155,  208,  267,  210,  220,
      373,  154,  366,  139,  220,  154,  222,  210,  210,  208,
      208,  160,  365,  160,  223,  219,  160,  161,  212,  212,
      212,  212,  154,  214,  214,  214,  214,  154,  222,  220,
      315,  223,  364,  160,  210,  271,  208,  160,  363,  223,
      358,  160,  209,  315,  213,  213,  213,  213,  273,  273,
      273,  273,  357,  355,  354,  209,  209,  209,  209,  213,
      271,  352,  351,  213,  350,  209,  209,  209,  209,  209,
      209,  221,  349,  221,  348,  347,  221,  221,  221,  221,

      213,  346,  209,  345,  343,  213,  209,  209,  209,  209,
      209,  209,  211,  309,  309,  309,  309,  311,  311,  311,
      311,  211,  211,  211,  211,  215,  215,  215,  215,  342,
      339,  211,  211,  211,  211,  211,  211,  338,  337,  330,
      215,  329,  325,  324,  215,  323,  322,  321,  211,  320,
      319,  318,  211,  211,  211,  211,  211,  211,  317,  316,
      307,  215,  269,  306,  269,  304,  215,  269,  269,  269,
      269,  270,  303,  270,  302,  301,  270,  270,  270,  270,
      274,  274,  274,  274,  300,  299,  310,  310,  310,  310,
      297,  296,  295,  294,  292,  274,  291,  290,  289,  274,

      286,  310,  285,  284,  283,  310,  282,  281,  280,  312,
      312,  312,  312,  278,  277,  276,  274,  275,  264,  263,
      261,  274,  310,  260,  312,  259,  258,  310,  312,  257,
      256,  255,  254,  253,  252,  251,  250,  248,  246,  245,
      242,  241,  240,  239,  236,  312,  234,  233,  232,  231,
      312,  388,  230,  388,  388,  388,  388,  388,  388,  388,
      389,  229,  389,  389,  389,  389,  389,  389,  389,  390,
      228,  390,  227,  390,  390,  390,  390,  390,  391,  391,
      391,  391,  392,  392,  226,  392,  225,  207,  392,  393,
      393,  206,  393,  205,  204,  393,  394,  203,  394,  394,

      394,  394,  394,  394,  394,  395,  395,  395,  396,  396,
      397,  397,  398,  398,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  190,  189,  187,  186,  185,
      184,  183,  182,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  164,  163,  158,
      157,  140,  136,  133,  132,  131,  128,  126,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  100,
       97,   93,   84,   73,   54,   49,   48,   46,   44,   43,
       41,   36,   35,   33,   26,   23,   15,   12,    9,    7,

        5,    3,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[111] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 26 "flex.l"
    #include <stdio.h>
    #include "bison.tab.h" //to get the tokens defined on bison file
    extern int flagGNUStyle;
    extern int flagBSDStyle;
    extern int teamStyle;
    extern int preprocessorFlag;
    extern int replaceFileFlag;
    char linebuf[500];
    int yycolumn = 1;
    extern void yyerror(const char *);  /* prints grammar violation message */
    extern int sym_type(const char *);  /* returns type from symbol table */

    #define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

    #define YY_USER_ACTION yycolumn += yyleng;\
    yylloc.first_line = yylloc.last_line = yylineno; \
    yylloc.first_column = yycolumn - yyleng; \
    yylloc.last_column = yycolumn -1;

    static void comment(void);
    static int check_type(void);
    extern int spaces;
    extern void printSpacesPretty();
#line 796 "lex.yy.c"
#line 797 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 51 "flex.l"


#line 1017 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 388 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 703 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "flex.l"
{return PREPROCESSING;} /* preprocessing instructions */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "flex.l"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "flex.l"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "flex.l"
{yylval.stringValue = strdup(yytext); return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "flex.l"
{yylval.stringValue = strdup(yytext); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "flex.l"
{yylval.stringValue = strdup(yytext); return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "flex.l"
{yylval.stringValue = strdup(yytext); return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 62 "flex.l"
{yylval.stringValue = strdup(yytext); return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "flex.l"
{yylval.stringValue = strdup(yytext); return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "flex.l"
{yylval.stringValue = strdup(yytext); return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "flex.l"
{yylval.stringValue = strdup(yytext); return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "flex.l"
{yylval.stringValue = strdup(yytext); return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "flex.l"
{yylval.stringValue = strdup(yytext); return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "flex.l"
{yylval.stringValue = strdup(yytext); return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "flex.l"
{yylval.stringValue = strdup(yytext); return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "flex.l"
{yylval.stringValue = strdup(yytext); return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "flex.l"
{yylval.stringValue = strdup(yytext); return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "flex.l"
{yylval.stringValue = strdup(yytext); return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "flex.l"
{yylval.stringValue = strdup(yytext); return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "flex.l"
{yylval.stringValue = strdup(yytext); return(INLINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "flex.l"
{yylval.stringValue = strdup(yytext); return(INT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "flex.l"
{yylval.stringValue = strdup(yytext); return(LONG); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "flex.l"
{yylval.stringValue = strdup(yytext); return(REGISTER); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "flex.l"
{yylval.stringValue = strdup(yytext); return(RESTRICT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "flex.l"
{yylval.stringValue = strdup(yytext); return(RETURN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "flex.l"
{yylval.stringValue = strdup(yytext); return(SHORT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "flex.l"
{yylval.stringValue = strdup(yytext); return(SIGNED); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "flex.l"
{yylval.stringValue = strdup(yytext); return(SIZEOF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "flex.l"
{yylval.stringValue = strdup(yytext); return(STATIC); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "flex.l"
{yylval.stringValue = strdup(yytext); return(STRUCT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "flex.l"
{yylval.stringValue = strdup(yytext); return(SWITCH); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "flex.l"
{yylval.stringValue = strdup(yytext); return(TYPEDEF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "flex.l"
{yylval.stringValue = strdup(yytext); return(UNION); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "flex.l"
{yylval.stringValue = strdup(yytext); return(UNSIGNED); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "flex.l"
{yylval.stringValue = strdup(yytext); return(VOID); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "flex.l"
{yylval.stringValue = strdup(yytext); return(VOLATILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "flex.l"
{yylval.stringValue = strdup(yytext); return(WHILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "flex.l"
{yylval.stringValue = strdup(yytext); return ALIGNAS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "flex.l"
{yylval.stringValue = strdup(yytext); return ALIGNOF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "flex.l"
{yylval.stringValue = strdup(yytext); return ATOMIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "flex.l"
{yylval.stringValue = strdup(yytext); return BOOL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "flex.l"
{yylval.stringValue = strdup(yytext); return COMPLEX; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 97 "flex.l"
{yylval.stringValue = strdup(yytext); return GENERIC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "flex.l"
{yylval.stringValue = strdup(yytext); return IMAGINARY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 99 "flex.l"
{yylval.stringValue = strdup(yytext); return NORETURN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 100 "flex.l"
{yylval.stringValue = strdup(yytext); return STATIC_ASSERT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 101 "flex.l"
{yylval.stringValue = strdup(yytext); return THREAD_LOCAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 102 "flex.l"
{yylval.stringValue = strdup(yytext); return FUNC_NAME; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 104 "flex.l"
{yylval.stringValue = strdup(yytext); return check_type(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "flex.l"
{yylval.stringValue = strdup(yytext); return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "flex.l"
{yylval.stringValue = strdup(yytext); return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 108 "flex.l"
{yylval.stringValue = strdup(yytext); return I_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "flex.l"
{yylval.stringValue = strdup(yytext); return I_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "flex.l"
{yylval.stringValue = strdup(yytext); return F_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "flex.l"
{yylval.stringValue = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 120 "flex.l"
{yylval.stringValue = strdup(yytext); return ELLIPSIS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 121 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHT_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 122 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFT_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "flex.l"
{yylval.stringValue = strdup(yytext); return ADD_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "flex.l"
{yylval.stringValue = strdup(yytext); return SUB_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "flex.l"
{yylval.stringValue = strdup(yytext); return MUL_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "flex.l"
{yylval.stringValue = strdup(yytext); return DIV_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "flex.l"
{yylval.stringValue = strdup(yytext); return MOD_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "flex.l"
{yylval.stringValue = strdup(yytext); return AND_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "flex.l"
{yylval.stringValue = strdup(yytext); return XOR_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 "flex.l"
{yylval.stringValue = strdup(yytext); return OR_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHT_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 132 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFT_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 "flex.l"
{yylval.stringValue = strdup(yytext); return INC_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 134 "flex.l"
{yylval.stringValue = strdup(yytext); return DEC_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 135 "flex.l"
{yylval.stringValue = strdup(yytext); return PTR_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 136 "flex.l"
{yylval.stringValue = strdup(yytext); return AND_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 137 "flex.l"
{yylval.stringValue = strdup(yytext); return OR_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 138 "flex.l"
{yylval.stringValue = strdup(yytext); return LE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 139 "flex.l"
{yylval.stringValue = strdup(yytext); return GE_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 140 "flex.l"
{yylval.stringValue = strdup(yytext); return EQ_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 141 "flex.l"
{yylval.stringValue = strdup(yytext); return NE_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 142 "flex.l"
{yylval.stringValue = strdup(yytext); return SEMMICOLON; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 143 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFTBRACKET; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 144 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHTBRACKET; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 145 "flex.l"
{yylval.stringValue = strdup(yytext); return COMMA; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 146 "flex.l"
{yylval.stringValue = strdup(yytext); return TWOPOINTS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 147 "flex.l"
{yylval.stringValue = strdup(yytext); return EQUALS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 148 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFTPAREN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 149 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHTPAREN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 150 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFTSQUAREBRACKET; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 151 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHTSQUAREBRACKET; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 152 "flex.l"
{yylval.stringValue = strdup(yytext); return POINT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 153 "flex.l"
{yylval.stringValue = strdup(yytext); return AND; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 154 "flex.l"
{yylval.stringValue = strdup(yytext); return EXCLAMATION; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 155 "flex.l"
{yylval.stringValue = strdup(yytext); return NOT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 156 "flex.l"
{yylval.stringValue = strdup(yytext); return MINUS; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 157 "flex.l"
{yylval.stringValue = strdup(yytext); return PLUS; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 158 "flex.l"
{yylval.stringValue = strdup(yytext); return ASTERISK; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 159 "flex.l"
{yylval.stringValue = strdup(yytext); return DIVITION; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 160 "flex.l"
{yylval.stringValue = strdup(yytext); return MODULUS; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 161 "flex.l"
{yylval.stringValue = strdup(yytext); return LEFTLESS; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 162 "flex.l"
{yylval.stringValue = strdup(yytext); return RIGHTMORE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 163 "flex.l"
{yylval.stringValue = strdup(yytext); return EXPONENTATION; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 164 "flex.l"
{yylval.stringValue = strdup(yytext); return OR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 165 "flex.l"
{yylval.stringValue = strdup(yytext); return TERNARYIF; }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 167 "flex.l"
{strncpy(linebuf, yytext+1, sizeof(linebuf)); /* save the next line */
        yyless(1);yycolumn =1;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 170 "flex.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 171 "flex.l"
{ /* discard bad characters */ }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 173 "flex.l"
ECHO;
	YY_BREAK
#line 1636 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 388 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 387);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "flex.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

void writePretty(){
    
}
